# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tu39ZUiKyAvwWnYwooiobCKwij1V7I_h
"""

pip install paho-mqtt

pip install psycopg2

import paho.mqtt.client as mqtt
import psycopg2

def on_connect(client, userdata, flags, rc):
    client.subscribe("/cahyo/temperature")

def on_message(client, userdata, msg):
    save(msg.payload)

def save(data):
    conn = psycopg2.connect(dbname="PY_Microcontroller",user="postgres", password="password", host="localhost", port="5432")
    cursor = conn.cursor()
    try:
        cursor.execute("INSERT INTO sensor_table (temperature) VALUES (%s)", (data))
        conn.commit()
        print("Data berhasil tersimpan")
    except (Exception, psycopg2.Error) as error:
        print(error)
    cursor.close()
    conn.close()

client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
client.on_connect = on_connect
client.on_message = on_message
client.connect("broker.hivemq.com", 1883, 60)
client.loop_forever()