# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tu39ZUiKyAvwWnYwooiobCKwij1V7I_h
"""

pip install paho-mqtt

import paho.mqtt.client as mqtt
from time import sleep

broker_address = "broker.hivemq.com"
broker_port = 1883
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
client.connect(broker_address, broker_port)

while True:
  data = 1
  client.publish("/cahyo/message", str(data))
  sleep(10)

